---
kind: ConfigMap
apiVersion: v1
metadata:
  name: wordpress-mysql-config
data:
  my.cnf: |-
    [mysqld]
    default_authentication_plugin=mysql_native_password
---
apiVersion: "mysql.oracle.com/v1"
kind: MySQLCluster
metadata:
  name: mysql-wordpress
spec:
  replicas: 1
  configRef:
    name: wordpress-mysql-config
  secretRef:
    name: wordpress-mysql-root-password
  volumeClaimTemplate:
    metadata:
      name: mysql-block-volume
    spec:
      storageClassName: "oci"
      selector:
        matchLabels:
          oci-availability-domain: "PHX-AD-1"
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:4.8.0-apache
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-wordpress-0.mysql-wordpress
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-mysql-root-password
              key: password
        ports:
        - containerPort: 80
